name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: "20"
      DOCKER_IMAGE_NAME: "josephdung.dev"
      DOCKER_IMAGE_TAG: "latest"
      DOCKER_TAR_FILE: "josephdung.dev.tar"
      VPS_TARGET_PATH: "/tmp/josephdung.dev.tar"
      # MONGODB_URI: ${{ secrets.MONGODB_URI }}
      # JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      # - name: Create or overwrite .env file
      #   run: |
      #     echo "MONGODB_URI=${{ env.MONGODB_URI }}" >> .env
      #     echo "JWT_SECRET=${{ env.JWT_SECRET }}" >> .env
      #     echo "SHOP_NAME=${{ env.SHOP_NAME }}" >> .env

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }} .

      - name: Save Docker image to tar file
        run: docker save ${{ env.DOCKER_IMAGE_NAME }} -o ${{ env.DOCKER_TAR_FILE }}

      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: ${{ env.DOCKER_TAR_FILE }}
          target: ${{ env.VPS_TARGET_PATH }}
          overwrite: true

      - name: Deploy Docker container on VPS
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker load -i ${{ env.VPS_TARGET_PATH }}
            docker stop ${{ env.DOCKER_IMAGE_NAME }} || true
            docker rm ${{ env.DOCKER_IMAGE_NAME }} || true
            docker run -d -p 3000:3000 --name ${{ env.DOCKER_IMAGE_NAME }} ${{ env.DOCKER_IMAGE_NAME }}
